[package]
name = "first_zome_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "first_zome_integrity"

[dependencies]
hdi = { workspace = true }

serde = { workspace = true }
